package com.example.springbootmiaosha.dao;

import com.example.springbootmiaosha.dataobject.ItemStockDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 07 16:48:23 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 07 16:48:23 CST 2020
     */
    int insert(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 07 16:48:23 CST 2020
     */
    int insertSelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 07 16:48:23 CST 2020
     */
    ItemStockDO selectByPrimaryKey(Integer id);


    ItemStockDO selectByItemId(Integer item_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 07 16:48:23 CST 2020
     */
    int updateByPrimaryKeySelective(ItemStockDO record);

    int  decreaseStock(@Param("itemId") Integer itemId,@Param("amount")  Integer amount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 07 16:48:23 CST 2020
     */
    int updateByPrimaryKey(ItemStockDO record);
}